import {unpack,makeCafe,comfort,place,storeAll,tickCafe,claim,interact,makeBattle,useSkill,tickBattle} from './model.mjs';
const app=document.querySelector('#app');
try {
  const fetchJson=async path=>{const r=await fetch(path);if(!r.ok)throw Error(`${path}: ${r.status}`);return r.json();};
  const [raw,tokens,evidence]=await Promise.all([fetchJson('../game-config.json'),fetchJson('../tokens.json'),fetchJson('../evidence/index.json')]);
  const c=unpack(raw),t=unpack(tokens);
  for(const [key,value]of Object.entries(t.colors))document.documentElement.style.setProperty('--'+key,value);
  let cafe=makeCafe(c),battle=makeBattle(c),mode='cafe',tool='browse',item='desk',rotated=false,skill=null,message='Select a visitor to greet them, or furnish the room.',reaction=null;
  let last=performance.now(),acc=0,lastRender=0;
  const reduced=matchMedia('(prefers-reduced-motion: reduce)');
  const pt=(x,z,h=0)=>[c.projection.originX+(x-z)*c.projection.tileX,c.projection.originY+(x+z)*c.projection.tileY-h];
  const points=coords=>coords.map(a=>pt(...a).join(',')).join(' ');
  const poly=(coords,fill,stroke='#96b5c9')=>`<polygon points="${points(coords)}" fill="${fill}" stroke="${stroke}"/>`;
  function chibi(x,y,color,label,halo=true){return `<ellipse cx="${x}" cy="${y}" rx="19" ry="7" fill="#57718b24"/><g transform="translate(${x},${y})"><path d="M-8-14L-9 0M8-14L9 0" stroke="#294663" stroke-width="8"/><path d="M-13-40Q0-48 13-40L17-15H-17Z" fill="${color}" stroke="#294663" stroke-width="1.5"/><path d="M-17-30L-22-14M17-30L22-14" stroke="#efd4c7" stroke-width="7" stroke-linecap="round"/><circle cy="-58" r="24" fill="#f8dfcf" stroke="#294663"/><path d="M-24-55Q-27-86 0-84Q28-83 24-52L11-72L2-57L-5-68L-16-53Z" fill="${color}"/><ellipse cx="-8" cy="-54" rx="3" ry="5" fill="#294663"/><ellipse cx="8" cy="-54" rx="3" ry="5" fill="#294663"/><path d="M-3-43Q0-40 4-43" stroke="#916576" fill="none"/>${halo?'<ellipse cy="-97" rx="20" ry="5" fill="none" stroke="#5cd6f5" stroke-width="3"/>':''}<text y="22" text-anchor="middle" fill="#294663" font-size="12">${label}</text></g>`;}
  function room(){const n=c.cafe.gridSize;let out=poly([[0,0,100],[n,0,100],[n,0],[0,0]],t.colors.wall)+poly([[0,0,100],[0,n,100],[0,n],[0,0]],'#d2e2ec');out+=poly([[0,0,30],[n,0,30],[n,0],[0,0]],t.colors.wallBand)+poly([[0,0,30],[0,n,30],[0,n],[0,0]],'#527fa6');out+=poly([[0,0],[n,0],[n,n],[0,n]],t.colors.floor);for(let x=0;x<n;x++)for(let z=0;z<n;z++){const verts=[[x,z],[x+1,z],[x+1,z+1],[x,z+1]];out+=`<g ${tool==='place'?`role="button" tabindex="0" aria-label="Place at ${x},${z}" data-x="${x}" data-z="${z}"`:''}>${poly(verts,tool==='place'?(x+z)%2?'#dbf0ea':'#e4f4ef':(x+z)%2?'#f2e8d4':'#f7efdf',tool==='place'?'#7baaac':'#ddcfb7')}</g>`;}return out;}
  function furniture(p){const f=c.furniture.find(f=>f.id===p.id),[x,y]=pt(p.x+p.w/2,p.z+p.d/2);if(p.id==='plant')return `<g><ellipse cx="${x}" cy="${y}" rx="16" ry="7" fill="#63856c22"/><path d="M${x-12} ${y-25}L${x-8} ${y}H${x+8}L${x+12} ${y-25}Z" fill="#c79c80"/><ellipse cx="${x}" cy="${y-25}" rx="12" ry="5" fill="#886b59"/><path d="M${x} ${y-24}v-36" stroke="#597a62" stroke-width="3"/><ellipse cx="${x-8}" cy="${y-46}" rx="10" ry="18" fill="${f.color}" transform="rotate(-30 ${x-8} ${y-46})"/><ellipse cx="${x+8}" cy="${y-58}" rx="10" ry="18" fill="#8bc2a4" transform="rotate(35 ${x+8} ${y-58})"/></g>`;const coords=[[p.x,p.z,28],[p.x+p.w,p.z,28],[p.x+p.w,p.z+p.d,28],[p.x,p.z+p.d,28]];return poly([[p.x,p.z+p.d,28],[p.x+p.w,p.z+p.d,28],[p.x+p.w,p.z+p.d],[p.x,p.z+p.d]],'#7097a7')+poly(coords,f.color)+(p.id==='sofa'?poly([[p.x,p.z,57],[p.x+p.w,p.z,57],[p.x+p.w,p.z,28],[p.x,p.z,28]],'#5493bb'):'');}
  function cafeScene(){let out=room();const draw=[...cafe.placed.map(p=>({depth:p.x+p.z+p.w/2+p.d/2,html:`<g pointer-events="none">${furniture(p)}</g>`})),...c.visitors.map(v=>{const [x,y]=pt(v.x,v.z);const bob=reduced.matches?0:Math.sin(cafe.time*2*Math.PI/t.motion.idlePeriod+v.x)*t.motion.idleAmplitude;const active=reaction?.id===v.id&&cafe.time<reaction.until;return {depth:v.x+v.z,html:`<g role="button" tabindex="0" aria-label="Greet ${v.label}" data-visitor="${v.id}">${chibi(x,y+bob,v.color,v.label)}${tool==='gift'||active?`<g><rect x="${x-35}" y="${y-142}" width="70" height="25" rx="12" fill="${v.favorite?t.colors.yellow:'white'}"/><text x="${x}" y="${y-125}" text-anchor="middle" fill="#294663" font-size="12">${active?'♥ +points':v.favorite?'♥ favorite':'☺ likes'}</text></g>`:''}</g>`};})];out+=draw.sort((a,b)=>a.depth-b.depth).map(d=>d.html).join('');return out;}
  function renderCafe(){app.innerHTML=`<section class="stage"><div class="topbar"><strong>Café / diorama study</strong><span id="wallet">Wallet ${cafe.wallet} · Gifts ${cafe.gifts}</span><span class="tag">ORIGINAL PLACEHOLDER ART</span></div><svg id="scene" viewBox="0 0 1020 610" aria-label="Oblique café room"><title>Café room with visitors and furnishings</title>${cafeScene()}</svg><div class="toolbar"><button data-action="edit" aria-pressed="${tool==='place'}">✥ Edit</button><button data-action="gift" aria-pressed="${tool==='gift'}" ${cafe.gifts?'':'disabled'}>♧ Gifts</button><button data-action="store">▤ Store all</button><button data-action="reset-cafe">Reset study</button><div class="stats" id="cafe-stats"></div><button class="claim" data-action="claim">Claim earnings</button></div>${tool==='place'?`<div class="tools">${c.furniture.map(f=>`<button data-item="${f.id}" aria-pressed="${item===f.id}">${f.label} · ${cafe.stock[f.id]} owned</button>`).join('')}<button data-action="rotate">Rotate (${rotated?'90°':'0°'})</button><button data-action="cancel">Cancel</button><p>Click a tile to place. R rotates. Overlaps and out-of-bounds placements are rejected.</p></div>`:''}<p class="hint" role="status" id="message">${message}</p></section>`;updateCafe();}
  function updateCafe(){document.querySelector('#cafe-stats').textContent=`Comfort ${comfort(cafe,c)} / ${c.cafe.comfortCap} · Bank ${Math.floor(cafe.bank)} / ${c.cafe.storage}`;document.querySelector('#wallet').textContent=`Wallet ${cafe.wallet} · Gifts ${cafe.gifts}`;}
  function renderBattle(){const s=battle;app.innerHTML=`<section class="stage"><div class="topbar"><strong>Combat / command study</strong><span class="tag">SIMPLIFIED PROPOSED RULES</span><div class="switches"><button data-action="auto" aria-pressed="${s.auto}">AUTO ${s.auto?'ON':'OFF'}</button><button data-action="pause">${s.paused?'Resume':'Pause'}</button><button data-action="restart">Restart</button></div></div><div class="battle-meta"><span id="battle-stats"></span><span id="battle-hp"></span></div><svg id="battle-scene" viewBox="0 0 1020 470" aria-label="Combat targeting area"><title>Four placeholder students and a practice target</title></svg><div class="toolbar">${c.skills.map(k=>`<button data-skill="${k.id}" aria-pressed="${skill===k.id}">${k.label} · ${k.cost} cost</button>`).join('')}<button data-action="cancel">Cancel target</button><span class="muted">Cost and HP are demo values.</span></div><div id="result"></div><p class="hint" role="status" id="message">${message}</p></section>`;updateBattle();}
  function updateBattle(){const s=battle;document.querySelector('#battle-stats').textContent=`Wave ${Math.min(s.wave+1,c.waves.length)} / ${c.waves.length} · Time ${Math.ceil(c.battle.timer-s.time)}s · Cost ${s.cost.toFixed(1)} / ${c.battle.costCap}`;document.querySelector('#battle-hp').textContent=`Team HP ${Math.ceil(s.hp)} / ${c.battle.teamHp} · Enemy HP ${Math.ceil(s.enemyHp)}${s.time<s.shieldUntil?' · SHIELDED':''}`;if(!document.activeElement?.closest('#battle-scene'))document.querySelector('#battle-scene').innerHTML=`<path d="M0 370L1020 170V470H0Z" fill="#dce7ed"/><path d="M50 430L940 250M50 310L940 130" stroke="#c5d8e2" stroke-width="2"/><g role="button" tabindex="0" aria-label="Target team" data-target="team">${c.visitors.map((v,i)=>chibi(170+i*105,330-i*20,v.color,'Striker '+(i+1))).join('')}${chibi(485,270,'#9db8a0','Striker 4')}<rect x="120" y="370" width="400" height="16" rx="8" fill="#bdd2df"/><rect x="120" y="370" width="${400*s.hp/c.battle.teamHp}" height="16" rx="8" fill="#6abda9"/>${skill&&c.skills.find(k=>k.id===skill).target==='team'?'<rect x="90" y="155" width="465" height="250" rx="20" fill="none" stroke="#168bbb" stroke-width="3" stroke-dasharray="8 5"/>':''}</g><g role="button" tabindex="0" aria-label="Target enemy" data-target="enemy"><ellipse cx="800" cy="278" rx="58" ry="20" fill="#29466320"/><rect x="755" y="185" width="90" height="80" rx="14" fill="#d7b2b4" stroke="#956574" stroke-width="3"/><rect x="770" y="205" width="60" height="24" rx="4" fill="#294663"/><circle cx="785" cy="218" r="5" fill="#f9e377"/><circle cx="815" cy="218" r="5" fill="#f9e377"/><text x="800" y="311" text-anchor="middle" fill="#294663">Practice target</text>${skill==='burst'?'<circle cx="800" cy="220" r="75" fill="none" stroke="#168bbb" stroke-width="3" stroke-dasharray="8 5"/>':''}</g>`;document.querySelector('#result').innerHTML=s.status==='running'?'':`<div class="result">${s.status==='victory'?'Stage clear':'Stage failed'} · Restart to try again.</div>`;document.querySelectorAll('[data-skill]').forEach(b=>b.disabled=s.status!=='running'||s.paused||s.cost<c.skills.find(k=>k.id===b.dataset.skill).cost);}
  function renderGallery(){app.innerHTML=`<div class="gallery">${evidence.media.map(e=>`<figure><a href="../evidence/${e.path}"><img src="../evidence/${e.path}" alt="${e.title}" loading="lazy"></a><figcaption><strong>${e.id} · ${e.title}</strong><br>${e.dimensions_px.join(' × ')} px · ${e.edition}<br><a href="${e.url}" target="_blank" rel="noopener">Original publisher image ↗</a> · reference only</figcaption></figure>`).join('')}</div>`;}
  function render(){if(mode==='cafe')renderCafe();else if(mode==='battle')renderBattle();else renderGallery();}
  function cancel(){tool='browse';skill=null;message='Cancelled. No uncommitted action was spent.';render();}
  function activate(el){if(!el||el.disabled)return;
    if(el.dataset.mode){mode=el.dataset.mode;tool='browse';skill=null;message=mode==='battle'?'Students attack automatically. Select a skill, then its indicated target.': 'Select visitors, place furniture, and claim earnings.';document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode));acc=0;render();return;}
    if(el.dataset.item){item=el.dataset.item;renderCafe();return;}
    if(el.dataset.x!==undefined){const error=place(cafe,c,item,Number(el.dataset.x),Number(el.dataset.z),rotated);message=error||'Furniture placed. Comfort and earnings rate increased.';if(!error)tool='browse';renderCafe();return;}
    if(el.dataset.visitor){const id=el.dataset.visitor;const error=interact(cafe,c,id,tool==='gift');message=error||`${c.visitors.find(v=>v.id===id).label}: relationship ${cafe.relationships[id]}`;if(!error){reaction={id,until:cafe.time+t.motion.reactionSeconds};tool='browse';}renderCafe();return;}
    if(el.dataset.skill){skill=el.dataset.skill;message=`${c.skills.find(k=>k.id===skill).label}: choose ${c.skills.find(k=>k.id===skill).target}. Escape cancels without spending.`;renderBattle();return;}
    if(el.dataset.target){if(!skill)return;const error=useSkill(battle,c,skill,el.dataset.target);message=error||'Command resolved.';if(!error)skill=null;renderBattle();return;}
    switch(el.dataset.action){case 'edit':tool=tool==='place'?'browse':'place';message='Choose a furniture item, then a floor tile.';break;case 'gift':tool=tool==='gift'?'browse':'gift';message='Preference preview: choose a recipient. This is the click alternative to drag/drop.';break;case 'store':storeAll(cafe,c);tool='browse';message='All furniture returned to inventory.';break;case 'rotate':rotated=!rotated;break;case 'claim':message=`Claimed ${claim(cafe)} credits.`;break;case 'reset-cafe':cafe=makeCafe(c);tool='browse';reaction=null;message='Café reset.';break;case 'cancel':cancel();return;case 'restart':battle=makeBattle(c);skill=null;message='Battle restarted.';break;case 'auto':battle.auto=!battle.auto;break;case 'pause':battle.paused=!battle.paused;acc=0;break;}render();}
  document.addEventListener('click',e=>activate(e.target.closest('button,[role=button]')));
  document.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const el=e.target.closest('svg [role=button]');if(el){e.preventDefault();activate(el);}}if(e.key==='Escape')cancel();if(e.key.toLowerCase()==='r'&&mode==='cafe'&&tool==='place'){rotated=!rotated;render();}if(e.key.toLowerCase()==='p'&&mode==='battle'){battle.paused=!battle.paused;acc=0;render();}});
  document.addEventListener('visibilitychange',()=>{last=performance.now();acc=0;});
  function frame(now){const dt=Math.min((now-last)/1000,c.simulation.frameCap);last=now;if(!document.hidden&&mode!=='gallery'){acc+=dt;while(acc>=c.simulation.step){if(mode==='cafe')tickCafe(cafe,c,c.simulation.step);else tickBattle(battle,c,c.simulation.step);acc-=c.simulation.step;}if(now-lastRender>100){if(mode==='cafe'){updateCafe();if(tool!=='place'&&!document.activeElement?.closest('#scene'))document.querySelector('#scene').innerHTML=cafeScene();}else updateBattle();lastRender=now;}}requestAnimationFrame(frame);}
  render();requestAnimationFrame(frame);
} catch(error){app.replaceChildren();const p=document.createElement('p');p.className='empty';p.setAttribute('role','alert');p.textContent=`Unable to load the study: ${error.message}. Serve the entire capture folder over HTTP.`;app.append(p);}
