import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {unpack,makeCafe,comfort,place,storeAll,tickCafe,claim,interact,makeBattle,tickBattle,useSkill} from './model.mjs';
const c=unpack(JSON.parse(await readFile(new URL('../game-config.json',import.meta.url),'utf8')));
const step=c.simulation.step;
let s=makeCafe(c);
assert.equal(place(s,c,'desk',9,9),'Outside room bounds');assert.equal(s.stock.desk,3);
assert.equal(place(s,c,'desk',3,3),null);assert.equal(s.stock.desk,2);assert.equal(comfort(s,c),120);
assert.equal(place(s,c,'sofa',3,3),'Furniture overlaps');assert.equal(s.stock.sofa,2);
assert.equal(place(s,c,'desk',9,0,true),null);assert.deepEqual([s.placed[1].w,s.placed[1].d],[1,2]);
tickCafe(s,c,10000);assert.equal(s.bank,c.cafe.storage);const wallet=s.wallet;assert.equal(claim(s),200);assert.equal(s.wallet,wallet+200);assert.equal(claim(s),0);
assert.equal(interact(s,c,'a'),null);assert.equal(interact(s,c,'a'),'Visitor tap is cooling down');tickCafe(s,c,c.cafe.tapCooldown);assert.equal(interact(s,c,'a'),null);
for(let i=0;i<c.cafe.initialGifts;i++)assert.equal(interact(s,c,'a',true),null);const rel=s.relationships.a;assert.equal(interact(s,c,'a',true),'No gifts remaining');assert.equal(s.relationships.a,rel);
storeAll(s,c);assert.equal(comfort(s,c),0);assert.equal(s.stock.desk,3);
let b=makeBattle(c);const cost=b.cost;assert.equal(useSkill(b,c,'burst','team'),'Choose the indicated target');assert.equal(b.cost,cost);assert.equal(useSkill(b,c,'burst','enemy'),null);assert.equal(b.cost,0);assert.equal(useSkill(b,c,'burst','enemy'),'Insufficient cost');
b=makeBattle(c);b.paused=true;const before=structuredClone(b);tickBattle(b,c,step);assert.deepEqual(b,before);
b=makeBattle(c);for(let i=0;i<6000&&b.status==='running';i++)tickBattle(b,c,step);assert.equal(b.status,'defeat');const failureSeconds=b.time;
b=makeBattle(c);b.auto=true;for(let i=0;i<6000&&b.status==='running';i++)tickBattle(b,c,step);assert.equal(b.status,'victory');const clearSeconds=b.time;
const end=structuredClone(b);tickBattle(b,c,step);assert.deepEqual(b,end);assert.deepEqual(makeBattle(c),makeBattle(c));
b=makeBattle(c);b.nextTeam=Infinity;b.nextEnemy=Infinity;b.time=c.battle.timer-step;tickBattle(b,c,step*2);assert.equal(b.status,'defeat');
console.log(JSON.stringify({result:'PASS',checks:['bounds and transactional rejection','overlap rejection','rotation footprint','storage cap and claim idempotence','tap cooldown','gift exhaustion','store all','skill target/cost guards','pause freeze','no-input defeat','AUTO clear','terminal freeze','restart initialization','timeout defeat'],noInputFailureSeconds:failureSeconds,autoClearSeconds:clearSeconds},null,2));
